 ---
 - name: WEB-SERVER-1-CI-CD-PROJECT, WEB-SERVER-2-CI-CD-PROJECT, LB-SERVER-CI-CD-PROJECT,NFS-SERVER-CI-CD-PROJECT and DB-SERVER-CI-CD-PROJECT
  hosts: WEB-SERVER-1-CI-CD-PROJECT, WEB-SERVER-2-CI-CD-PROJECT, LB-SERVER-CI-CD-PROJECT,NFS-SERVER-CI-CD-PROJECT and DB-SERVER-CI-CD-PROJECT
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest
tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest